export const members = [
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  {
    name: "Shrilakshmi Pai",
    role: "President",
    img: "/team/team2022/shrilaxmi.png",
    github: "https://github.com/ShrilakshmiPai",
    linkedin: "https://www.linkedin.com/in/shrilakshmipai",
  },
  
];
